{{- if and .Values.ollama.enabled .Values.storage.ollama.persistentVolume.enabled (not .Values.storage.ollama.ephemeral) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ai-workshop.fullname" . }}-ollama-pvc
  labels:
    {{- include "ai-workshop.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama-server
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.ollama.persistentVolume.storageClass }}
  storageClassName: {{ .Values.storage.ollama.persistentVolume.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.ollama.persistentVolume.size }}
{{- end }}
