apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-secret
  namespace: {{ include "postgresql.namespace" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
data:
  postgresql-password: {{ .Values.secrets.postgresql.password | b64enc | quote }}
  pgadmin-password: {{ .Values.secrets.pgadmin.password | b64enc | quote }}